### ISSUE TITLE
issues starting

### ISSUE THREAD

**Issue by jbarneson** [koalazak/rest980#12]
looking for help -- new to nodejs. When I run npm start, I get a dependency error.. appreciate any help. FWIW - I have dorita running and I was able to get the blid and pw for the rest980 config file..

:~/rest980 $ npm start

> rest980@1.5.3 start /home/pi/rest980
> node ./bin/www

/home/pi/rest980/node_modules/dorita980/index.js:2
let cloud = require('./lib/cloud');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/rest980/routes/api.js:4:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! rest980@1.5.3 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the rest980@1.5.3 start script.
npm ERR! This is most likely a problem with the rest980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls rest980

**Comment by koalazak** [comment]
sounds like you have a very old nodejs version. what version you have installed? ( 'node -v' )

**Comment by jbarneson** [comment]
v0.10.29 -- thanks for replying.. this is my first attempt at using nodejs, need to get up to speed. Appreciate the help.

**Comment by koalazak** [comment]
dorita980 is compatible with node.js 4.0 to 7.0. 
to upgrade download the node.js 4 source code for your platform and compile:

cd source
./configure
make
sudo make install

in debian you need build-essential package instaled

**Comment by jbarneson** [comment]
alls working. Much appreciate the pointer.
