### ISSUE TITLE
Spot clean on map

### ISSUE THREAD

**Issue by maxbaeumle** [koalazak/rest980#13]
Maybe show the coordinates where the robot decided to perform a spot clean on the map. Is this possible?

**Comment by maxbaeumle** [comment]
Also cool would be different stroke color for when carpet boost was used / for Wi-Fi signal strength.

**Comment by koalazak** [comment]
do you know where is the data for that? what properties change in wich methods when that events happens?

**Comment by maxbaeumle** [comment]
Maybe in `getBprun()`?

**Comment by maxbaeumle** [comment]
Wi-Fi might not be possible, if the signal strength is only for the base station.

**Comment by koalazak** [comment]
reopen if you found the field
