### ISSUE TITLE
Getpassword in RES980

### ISSUE THREAD

**Issue by roelbroersma** [koalazak/rest980#18]
Wouldn't it be cool to have the Getpassword method in the REST980 interface?

Since issue #11 (of dorita) it is already in the dorita package.  But not yet in the rest980.

I helped a few people in setting up their robot with the rest library (on a synology) and noticed it was quite a job to get the password (install nodes, etc. on a Windows PC sucks) and installing an Ubuntu release with VNC on a synology, install git, nodes, etc. takes more than 1 hour time..

**Comment by roelbroersma** [comment]
Ah,. I see it is already mergerd but it was not mentioned in the Readme.. ?

**Comment by koalazak** [comment]
Its here, but not docummented cos its not the scope of this implementation. And to not have the getpassword documentation duplicated in two repos.

**Comment by roelbroersma** [comment]
Sorry to open this one again.. But I how do you request that thing from the Docker Image?

Because when you don't fill in a BLID/Password/IP, the image crashes/reboots.  So you cannot login to the docker container to manually execute the getpassword script.  I see it is in package.json: https://github.com/koalazak/rest980/blob/master/package.json, but how to call it.. (from docker) ?

**Comment by koalazak** [comment]
You should not use the getpassword in rest980. Use it in dorita980 to get our password and fill the ENV variables with that blid/password to start the docker in rest980.
If you still want to use getpassword on rest980 you cant using with the docker way.
getpassword is in rest980 only for debug purpose.

**Comment by roelbroersma** [comment]
Thats what I mean.  Shouldn't thee be an easy for for People to get the password? 
Most people don't have a development environment wide Nodes on it.
Imagine most households just have a Nas (Synology), an iPad, windows PC and/or Mac.  Now,. There is no Dorita docker image.  So they need to setup nodejs (and git), get the dorita gettpassword script.. run it.

For me on my development machine it is easy. But can't we make a Blackdoor in rest980 to get the password so people with just a synology nas (or hyper-v 2016 which also runs docker images out of the box) can get their password without all the hassle..
