### ISSUE TITLE
Roomba 960 support?

### ISSUE THREAD

**Issue by ersan** [koalazak/rest980#20]
Apologies if this is answered somewhere, but does this support the Roomba 960?  It seems to have the same connectivity as the 980 but is quite a bit cheaper.

**Comment by koalazak** [comment]
yes

**Comment by LaurensVanAcker** [comment]
And the Roomba 966? I guess that's also the same, except some battery and power differences.

**Comment by koalazak** [comment]
Hi @LaurensVanAcker do you own a 966? can you try dorita980 please and confirm?

**Comment by LaurensVanAcker** [comment]
Not yet, but because I want to integrate with OpenHab I want to be sure it works. If not I would rather buy the 980. But I guess if it doesn't, the changes shouldn't be that big and I would be able to make those changes.
