### ISSUE TITLE
Can not start

### ISSUE THREAD

**Issue by maduuto** [koalazak/rest980#28]
Hello. I get the error:

 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rest980@2.0.5~prestart: rest980@2.0.5
6 silly lifecycle rest980@2.0.5~prestart: no script for prestart, continuing
7 info lifecycle rest980@2.0.5~start: rest980@2.0.5
8 verbose lifecycle rest980@2.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle rest980@2.0.5~start: PATH: /usr/lib/node_modules/npm/bin/no$
10 verbose lifecycle rest980@2.0.5~start: CWD: /home/se.ki/node_modules/rest980
11 silly lifecycle rest980@2.0.5~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle rest980@2.0.5~start: Returned: code: 1  signal: null
13 info lifecycle rest980@2.0.5~start: Failed to exec start script
14 verbose stack Error: rest980@2.0.5 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib$
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn$
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:$
15 verbose pkgid rest980@2.0.5
16 verbose cwd /home/se.ki/node_modules/rest980
17 error Linux 4.9.59-v7+
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.12.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error rest980@2.0.5 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the rest980@2.0.5 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rest980 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs rest980
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls rest980
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can u help me?

**Comment by koalazak** [comment]
did you run `npm install` before `npm start`?

**Comment by maduuto** [comment]
I found the mistake, there was an error in password... its 1 instead of l :D so everything works now
