### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by yveshanoulle** [koalazak/rest980#31]
Hi, 
When I read the readme, I assume you want to software installed on the openhab server.
I try to keep my different services seperate.
Any experience with installing this on a seperate machine? If yes what is the minimum you need?
Is a raspberry PI 3 model B enough?

**Comment by koalazak** [comment]
rest980 is completly standalone and no need to be installed on openhab server. You can install rest980 in other individual server and make HTTP/S calls to it from wherever you want (if both sides can see each other in your network).
I have rest980 installed in a raspberry PI 3 and works fine.
