### ISSUE TITLE
Running on Docker (on Synology) gives me an error suddenly (crash)

### ISSUE THREAD

**Issue by roelbroersma** [koalazak/rest980#34]
Hello,

I;ve been using the REST980 for quite some time.  However, I noticed it was in a reboot loop (last week).

So I took a screenshot of all my settings.  Then deleted the container,  deleted the image.  Then did a new install (all on Synology/Docker) and entered my settings again.

It still keeps rebooting.   The following is the terminal output.

![image](https://user-images.githubusercontent.com/7059138/39997575-b1ffa908-5783-11e8-94ed-f7bda8d9fb08.png)

**Comment by koalazak** [comment]
Hi, the `Not authorized` message sounds like you robot changed his password. Or your config file or env variables are missing.
What robot version you have?

**Comment by roelbroersma** [comment]
I did the password-retrieve method again and with that password it works.

Strange.  It looks like the password is changed,  (is that possible between firmware 1 -> 2  or something.. ?)

It was a quite simple password, almost the same format (length) as the BLID), but now it is a complete string with some special characters in it.


Anyway, ticket can be closed.  Thanks!

~Roel

**Comment by koalazak** [comment]
nice!
Yes, password changes from firmware 2.
