### ISSUE TITLE
Docker config mismatch

### ISSUE THREAD

**Issue by dominikkv** [koalazak/rest980#35]
Hi,

in your Dockerfile, you set the env var NODE_ENV to "production". This causes the REST framework to look for the configuration file "config/production.json", resulting either in a warning (if you provide blid, pw & ip through env var):

> WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
> WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

or in an exception:

> /usr/src/app/routes/api.js:21
>   throw new Error('Config not found. Please edit config/default.json file with your robot credentials. Or set BLID, PASSWORD and ROBOT_IP enviroment variables.');
> ...

Thanks
Dominik

**Comment by koalazak** [comment]
Hi @dominikkv, 
The warning is the expected behavior. Just ignore it or create a production.json file with the required values.
The exception only happen if you do not fill the config/default.json file AND do not set the requred env variables.
