### ISSUE TITLE
Actions are not working

### ISSUE THREAD

**Issue by tobiasramin** [koalazak/rest980#36]
Hi,
first of all, thanks for your effort to create thos repo and Dockerfile. It cost me only a hour to get the Rest-Server running.

The Server can get preferences, missing etc, but all mentioned Actions are not working. 

E.g. 

Get http://syn:3000/api/local/action/start

Resonse: {
    "ok": null
}

iRobot Firmware: 2.4.6-3

I double cheked with map, but even there no activities.

Do you have an idea?

**Comment by koalazak** [comment]
Hi @tobiasramin, I just tested rest980 with the latest firmware (2.4.6-3) and actions are working fine.
How looks your configuration or env variables? Lets continue the talk in the other issue that you opened in dorita980
