### ISSUE TITLE
Roomba 980 reject requests

### ISSUE THREAD

**Issue by Goshi45** [koalazak/rest980#38]
Hello,

I'm sending request to my Roomba980 every minute using rest980 because I need to know if bin is full or not. If it's full, my Karotz say it until I move my lazy ass.

Sometimes, everything in ./api/local loads forever and never gives me an answer but : 
-I can see ./ or ./api/
-I'm still able to ping Roomba from my local server where rest980 is installed
-iRobot app loads correctly, in LTE and Wifi.
-Restarting rest980 doesn't fix the issue
-Restarting Roomba sometimes fix the issue, if not, I need to reset Roomba and get a new password

Any idea ?

Thanks.
Goshi.

**Comment by koalazak** [comment]
Hi, what value do you have in `keepAlive` option? I recomend to you use it on 'no' value.
The robot only can handle 1 connection at time (mobile app or rest980, or other). And if one connection is stablished then other devices can't connect. Close the mobile app and soft restart the roomba. Try to do not use the mobile app at the same time (hard if you are requesting every 1 min)

**Comment by Goshi45** [comment]
keepalive is already set to 'no'. 

My Roomba is currently ignoring my rest980 server, I already soft restarted it (pressing Clean button until I hear a sound) but it still doesn't load rest980. I will have to reset it.

My Google Home + IFTTT + rest980 starts Roomba when I'm leaving my home.
I use iRobot app only when rest980 is not loading. 

I noticed rest980 stops loading right after Roomba is full because Karotz says it's full like 2 or 3 times and then stops because rest980 stops answering.
That means there is no problem requesting every minute for days until Roomba is full.

I'll try sending less requests and will answer again in a few days then.

**Comment by Goshi45** [comment]
So I changed it to a request every 10 minutes. After a few hours, Roomba answered again without a reboot or reset but today it happened again :(.

I'll try with "keepalive" set to 'yes'.
