### ISSUE TITLE
Request to add Dockerfile to repo

### ISSUE THREAD

**Issue by allanglen** [koalazak/rest980#4]
I'm using your Docker image (https://hub.docker.com/r/koalazak/rest980/) on my NAS. I assume you are building that externally and then pushing up to the Docker Hub.

It would be helpful to add the Dockerfile to this repo to:
1) Allow local build and testing in Docker from source
2) Enable automatic build and publish to the Docker Hub (see (https://hub.docker.com/r/koalazak/rest980/)~/settings/automated-builds/

Thanks and excellent work!

**Comment by koalazak** [comment]
Sure! great idea!
After merge your other pull request i will push the file over your changes.

thanks!

**Comment by koalazak** [comment]
done!
thanks!
