### ISSUE TITLE
Error: Connection refused: Not authorized

### ISSUE THREAD

**Issue by Sturmchen** [koalazak/rest980#43]
**Error message:**
> rest980@2.0.8 start /opt/loxberry/rest980
> node ./bin/www

/opt/loxberry/rest980/node_modules/dorita980/lib/v2/local.js:32
    throw e;
    ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/opt/loxberry/rest980/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/opt/loxberry/rest980/node_modules/mqtt/lib/client.js:350:12)
    at work (/opt/loxberry/rest980/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/opt/loxberry/rest980/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/opt/loxberry/rest980/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/loxberry/rest980/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/opt/loxberry/rest980/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)

npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! rest980@2.0.8 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rest980@2.0.8 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rest980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rest980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rest980
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path npm-debug.log.2013081302
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2013081302'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.2013081302'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.2013081302' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/loxberry/rest980/npm-debug.log

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rest980@2.0.8~prestart: rest980@2.0.8
6 silly lifecycle rest980@2.0.8~prestart: no script for prestart, continuing
7 info lifecycle rest980@2.0.8~start: rest980@2.0.8
8 verbose lifecycle rest980@2.0.8~start: unsafe-perm in lifecycle true
9 verbose lifecycle rest980@2.0.8~start: PATH: /usr/lib/node_modules/npm/bin/no$
10 verbose lifecycle rest980@2.0.8~start: CWD: /opt/loxberry/rest980
11 silly lifecycle rest980@2.0.8~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle rest980@2.0.8~start: Returned: code: 1  signal: null
13 info lifecycle rest980@2.0.8~start: Failed to exec start script
14 verbose stack Error: rest980@2.0.8 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib$
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib$
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pro$
15 verbose pkgid rest980@2.0.8
16 verbose cwd /opt/loxberry/rest980
17 error Linux 4.4.13-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error rest980@2.0.8 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the rest980@2.0.8 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rest980 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www

**Comment by koalazak** [comment]
bad username or password
