### ISSUE TITLE
Unable to start npm

### ISSUE THREAD

**Issue by loxtom** [koalazak/rest980#45]
I was using rest980 for quite some time on my Raspberry Pi and a Roomba980 without any issues. A few weeks ago it stoped working and I could not solve the issue, so I reinstalled rest980 again but it fails already when starting. Below the message I receive. Thanks for your feedback.

root@loxberry:/opt/roomba/rest980# npm start
> rest980@2.0.8 start /opt/roomba/rest980
> node ./bin/www
Port 3000 is already in use
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rest980@2.0.8 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rest980@2.0.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-16T20_50_00_799Z-debug.log

root@loxberry:~/.npm/_logs# tail 2019-10-16T20_50_00_799Z-debug.log
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.1
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error rest980@2.0.8 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the rest980@2.0.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
root@loxberry:~/.npm/_logs#

**Comment by koalazak** [comment]
`Port 3000 is already in use`
You have something running on port 3000. Check with `ps` your process and kill it.
