### ISSUE TITLE
Node-RED

### ISSUE THREAD

**Issue by Mannshoch** [koalazak/rest980#50]
Please create a nodered app, may take one of these as a base [1](https://github.com/yuchangyuan/node-red-contrib-roomba980-fw2), [2](https://flows.nodered.org/node/node-red-contrib-roomba980)

There only two tools at nodered for Roomba 980 which both use your repo [flows.nodered.org/..](https://flows.nodered.org/search?term=roomba980) But it seems they do not anymore update. It would be nice if there is an updated repo and may in future an UI_Dashboard with the "Realtime Map". 

At moment, I use Node-RED with App [1](https://github.com/yuchangyuan/node-red-contrib-roomba980-fw2) at Home for command my Roomba by a CalDAV Calendar. 

If you need I would like to be a beta tester for the nodered repo.

**Comment by koalazak** [comment]
PRs are welcome
