### ISSUE TITLE
msg.ok.pos is undefined

### ISSUE THREAD

**Issue by Utopiah** [koalazak/rest980#55]
Everything works well except trying to draw the map, getting a `msg.ok.pos is undefined` error in the console.

I doubt it's related but just in case for context : Firefox 82.0 (64-bit) on Ubuntu with a Roomba 676.

**Comment by koalazak** [comment]
looks like Romba 676 does not report his possition to draw the map

**Comment by Utopiah** [comment]
Damn... well that's disappointed but now I know, thanks. Maybe adding this to the ReadMe and adding a related error message could help others in the future.
