### ISSUE TITLE
Dockerfile using sources

### ISSUE THREAD

**Issue by allanglen** [koalazak/rest980#6]
Just a quick note that you can put a Dockerfile at the project root and build from sources instead of doing a git clone during the docker build.  This allows building in Docker from local sources before the changes make their way to master. The Dockerfile would look like this:

```
# Use latest node
FROM node:boron

MAINTAINER koalazak <zak.tux@gmail.com>

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Set the node env (we only need production dependencies in the deployed image)
ENV NODE_ENV production

# Install dependencies (we deliberately just copy packages.json so we can use the cache if no package.json changes are made)
COPY package.json /usr/src/app/
RUN npm install

# Copy the sources
COPY . /usr/src/app

# Set default env
ENV BLID=
ENV PASSWORD=
ENV ROBOT_IP=
ENV PORT=3000

EXPOSE ${PORT}

# Start the REST interface!
CMD [ "npm", "start" ]
```

You can then build locally with:
```
docker build . -t koalazak/rest980 
```

This setup also works with automated builds on Docker Hub since it will pull the latest master before building.

**Comment by koalazak** [comment]
like it

**Comment by koalazak** [comment]
updated. can you test both scenarios? Install and run from the docker hub and from local?
thanks!
