### ISSUE TITLE
/api/local/info/state returns {}

### ISSUE THREAD

**Issue by ostpol** [koalazak/rest980#62]
I'm running rest980 on Node.js 14.16.0 to control my i7 running on 3.12.8.

```/api/local/info/state``` returns ```{}``` while other endpoints like ```/api/local/info/mission``` or ```/api/local/action/pause``` are working as expected.

default.json
```
{
  "port": 3000,
  "blid": "myBlid",
  "password": "myPw",
  "robotIP": "192.168.1.140",
  "firmwareVersion": 2,
  "enableLocal": "yes",
  "enableCloud": "no",
  "keepAlive": "no",
  "basicAuthUser": null,
  "basicAuthPass": null,
  "sslKeyFile": null,
  "sslCertFile": null
}
```

Any ideas? What other informations should I provide for troubleshooting?

**Comment by koalazak** [comment]
try with the latest version
