### ISSUE TITLE
/api/local/action/dock unable to find dock

### ISSUE THREAD

**Issue by SerhiiAksiutin** [koalazak/rest980#63]
When started by  `/api/local/action` and then stopped and requested to dock it can't seem to find way home. In the iRobot app it works as expected. 

Another observation is that when it started via REST the iRobot app can't seem to connect to the robot.

**Comment by SerhiiAksiutin** [comment]
It seems like v3 doesn't support the map

**Comment by koalazak** [comment]
follow on https://github.com/koalazak/dorita980/issues/148
