### ISSUE TITLE
Unable to load position data on i7+

### ISSUE THREAD

**Issue by JohnNeville** [koalazak/rest980#64]
I was running this successfully in HomeAssistant for a while and recently something changed that has caused it to go haywire. 

When I go to `http://127.0.0.1:9567/api/local/info/state' I get the following 

```
  "cap": {
    "binFullDetect": 2,
    "oMode": 10,
    "dockComm": 1,
    "wDevLoc": 2,
    "bleDevLoc": 1,
    "edge": 0,
    "maps": 3,
    "pmaps": 5,
    "tLine": 2,
    "area": 1,
    "eco": 1,
    "multiPass": 2,
    "team": 1,
    "pp": 0,
    "lang": 2,
    "hm": 0,
    "5ghz": 1,
    "prov": 3,
    "sched": 1,
    "svcConf": 1,
    "ota": 2,
    "log": 2,
    "langOta": 0,
    "tileScan": 1
  }
```

I did notice that this is in here as well:
```
"featureFlags": {
    "quietNav": true,
    "homeMonitoring": false,
    "clearHaz": true,
    "hibLed": 0,
    "covPlan": 0,
    "ros2SptLvl": true
  }
```

My dock appears to be `"fwVer": "4.2.3"`  and I see `"softwareVer": "lewis+3.20.7+lewis-release-rt421+11"` for the i7 itself. 

Is there anyway to debug the messages that the device is actually sending?

**Comment by dewoert** [comment]
Same problem here. seems related to firmware update on the Roomba 3.20.7 ?

**Comment by tobuh** [comment]
Same here ...
Firmware 3.20.7, last updated on October 27, 2021
As far as I remember, from there on I could not get any positioning data for my map (home-assistant)
I think, downgrading is not possible? :-/

**Comment by crissmil** [comment]
Same here for Roomba S9+ after v3.20.7 no pose available. I believe dorita needs an update

**Comment by crissmil** [comment]
Today also my Braava m6 updated to v3.20.7 and "pose" data disappeared. Any ideas?

**Comment by mattibijnens** [comment]
I'm experiencing the same issue on the I7+. Position data seems to be missing since software 3.20.7

**Comment by darek-margas** [comment]
And mine too, also v3.20.7 updated on 11/Nov and since then no trace of location

**Comment by darek-margas** [comment]
Do we have any hope?

**Comment by rszemplinski** [comment]
My pos data disappeared as well

**Comment by generalk25** [comment]
Same issue here. Any updates on what to do to correct this?

**Comment by henripalmroth** [comment]
I think it will be here when something happens. At least it is good to give feedback to iRobot.

https://github.com/koalazak/dorita980/issues/148

**Comment by tfili** [comment]
I'm also seeing it.

**Comment by koalazak** [comment]
follow the firmware changes in https://github.com/koalazak/dorita980/issues/148
