### ISSUE TITLE
Dead after starting

### ISSUE THREAD

**Issue by s2nrbald** [koalazak/rest980#65]
After executing npm install, I get this and then it hangs.  This is a first time setup on an i7.  DLID and PWD are in the config file correctly.

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@6.8.0 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

audited 367 packages in 5.915s

6 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (4 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
loxberry@loxberry:~/rest980/rest980 $ npm start                                 
> rest980@2.1.2 start /opt/loxberry/rest980/rest980
> node ./bin/www

**Comment by koalazak** [comment]
where is the hang? process is now listening for http requests
