### ISSUE TITLE
Sometimes looses connection ...

### ISSUE THREAD

**Issue by rotdrop** [koalazak/rest980#66]
Hi,

kind thanks for this nice toy! I have the issue that the rest-daemon sometimes -- even in the middle of cleaning -- looses the connection to the Roomba (which is a 960 model). I can restart the Bot by pressing the pwr-btn for a long time and releasing, and the the rest-daemon connects again.

Is this somehow known, or is there a known work-around? I did not yet dig deeper ...

**Comment by koalazak** [comment]
sometimes another appliation may takes over the connection to the robot. Robot support only one connection at once
