### ISSUE TITLE
Timeour errors in rest980/dorita980

### ISSUE THREAD

**Issue by ludekvodicka** [koalazak/rest980#7]
Hi there,
I'm trying your tools for roomba980 but I'm getting a lot of timeout errors. 

Every RestPoint/function which leads only to your local methods (root API point, /map,...) are proceed immediately, but any connection to Roomba usually leads to a timeout. Sometime command is proceeded after 3-5minutes.

But commands made from iRoomba app (connected to the same network) are proceed withing few msec.

```
RequestError: Error: connect ETIMEDOUT 192.168.6.109:443
    at new RequestError (/home/dev/rest980/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/dev/rest980/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/dev/rest980/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/dev/rest980/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/dev/rest980/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1256:8)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Do you have any idea where can be a problem? I tried it on several places on my home where wifi signal is strong enough for any other device and it seems that this is not a problem.

Thank you
Ludek

**Comment by ludekvodicka** [comment]
it seems that Roomba is able to receive/send about 3-4packets from rest980 and then problems with timeouts occur again - http://screencast.com/t/7JspkIhVe

And this is what is captured via map - http://screencast.com/t/fHlwkRUNhOQ

**Comment by koalazak** [comment]
Hi @ludekvodicka,
what roomba firmware version you have? (use getSys method and view `sw` property).
Maybe you haven an firewall or other protection preventing DDOS attacks on your network? 
/map hits every 800ms maybe thath donest like to your firewall, try incrementing this time.
And try disconnecting your mobile app (to have only one `request id` consistent).

Are you sure you have only one docker container running? maybe by error you have a lot of docker containers hiting the roomba.

**Comment by ludekvodicka** [comment]
Thanks for replies (and for all work you did with Roomba API).

Roomba has 1.6.6 version (based on info in mobile app, I'm not able to execute getSys() method. I'm getting  `myRobotViaCloud.getSys is not a function`)

There shouldn't be any firewall or network shaper inside the network. From outside there is a firewall installed on OpenWRT router (Turis Omnia) but nothing inside.

Regarding the app, it's not a docker but new latest Ubuntu Server installed only for this purpose inside the free ESXI instance.

I tried to restart rest-server and tried it again when Roomba was in sleeping/charging mode. First few requests were without problems (I tried map->Test Sys) but after that ETIMEDOUT occurs again.

http://screencast.com/t/4K1gY0b83lD

And although rest980 wasn't able to connect to roomba, connections made from the mobile app was without problems.

**Comment by ludekvodicka** [comment]
One more observation. It seems that only rest980 doesn't work. I tried to click on TestSys button where I'm still getting "loading" and exceptions inside the console. But when I tried to call myapp.js based on your example where getStatus() is called, the connection was successful.

http://screencast.com/t/WTxTRIoR

But I'm not sure if getStatus() communicates with Roomba or returning only some local values.

**Comment by koalazak** [comment]
Yes, getStatus communicates with Roomba.
Seems to be a network issue. Try to leave a ping command running for a while from home-server to Roomba's ip address and watch if sudentry the comuncation is cutoff (meantime you are mapping).

**Comment by ludekvodicka** [comment]
As expected, getStatus doesn't work. So it's probably something with local communication.

http://screencast.com/t/QKnxrlLf9

But pings (from the inner network and outer too) works ok (only a little delay from 2ms to 12ms when command is executed). So I'm not sure what can cause it. But tomorrow I will install new wifi AP and try it again. 

I will try it tomorrow and let you know.

**Comment by koalazak** [comment]
Note in dorita980 documentation:
getStatus() is inside the returned object by Cloud() class.
```
var myRobotViaCloud = new dorita980.Cloud('MyUsernameBlid', 'MyPassword');
```
getMission() and getSys() are inside Local() class.
```
var myRobotViaLocal = new dorita980.Local('MyUsernameBlid', 'MyPassword', '192.168.1.104');
```

Try to run rest980 from sources outside docker. download this repo and run `npm install` then `npm start` (after edit config/default.json file).
Maybe there an issue in the network configuration of your docker VM machine brindge or something.
But is sure there a network issue.

**Comment by ludekvodicka** [comment]
Thanks. I already found that there are two classes ;-).

Regarding your docker note. I'm testing it on classic Ubuntu environment exactly like you wrote. repo+install+start

**Comment by ludekvodicka** [comment]
Ok, it was a false alarm. Today I installed new Wifi APs (Unifi AP-AC-LR) and Roomba and your software works perfectly.
