### ISSUE TITLE
Internal Server Error: host is required

### ISSUE THREAD

**Issue by raven-worx** [koalazak/rest980#72]
After some time running the server on my RaspberryPi (via docker in host network mode) i receive the following "Error: host is required" Internal Server Error for HTTP requests. Unfortunately i cant tell yet how long the server has to run to make this error occur.
It works when i restart the container/server right after though.

I run the docker container with the following commnad:

> docker run --rm --name=roomba-api --net=host -e PORT=3000 -e BLID=XXXXXX -e PASSWORD=XXXXX -e FIRMWARE_VERSION=2 -e ENABLE_LOCAL=yes -e ENABLE_CLOUD=no -e KEEP_ALIVE=no ravenworx/rest980:armv8

Log output:

> Aug 07 02:14:30 mypi roomba-api[482]: GET /api/local/info/state 500 3.796 ms - 148
Aug 07 02:14:30 mypi roomba-api[482]: Error: host is required.
Aug 07 02:14:30 mypi roomba-api[482]:     at localV2 (/usr/src/app/node_modules/dorita980/lib/v2/local.js:8:20)
Aug 07 02:14:30 mypi roomba-api[482]:     at new local (/usr/src/app/node_modules/dorita980/index.js:17:10)
Aug 07 02:14:30 mypi roomba-api[482]:     at sendAndDisconnect (/usr/src/app/routes/api.js:158:16)
Aug 07 02:14:30 mypi roomba-api[482]:     at /usr/src/app/routes/api.js:149:14
Aug 07 02:14:30 mypi roomba-api[482]:     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
Aug 07 02:14:30 mypi roomba-api[482]:     at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
Aug 07 02:14:30 mypi roomba-api[482]:     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
Aug 07 02:14:30 mypi roomba-api[482]:     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
Aug 07 02:14:30 mypi roomba-api[482]:     at /usr/src/app/node_modules/express/lib/router/index.js:284:15
Aug 07 02:14:30 mypi roomba-api[482]:     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
Aug 07 02:14:30 mypi roomba-api[482]:     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
Aug 07 02:14:30 mypi roomba-api[482]:     at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:175:3)
Aug 07 02:14:30 mypi roomba-api[482]:     at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
Aug 07 02:14:30 mypi roomba-api[482]:     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
Aug 07 02:14:30 mypi roomba-api[482]:     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
Aug 07 02:14:30 mypi roomba-api[482]:     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
Aug 07 02:14:30 mypi roomba-api[482]:     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
Aug 07 02:14:30 mypi roomba-api[482]:     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
Aug 07 02:14:30 mypi roomba-api[482]:     at /usr/src/app/node_modules/express/lib/router/index.js:646:15
Aug 07 02:14:30 mypi roomba-api[482]:     at next (/usr/src/app/node_modules/express/lib/router/index.js:265:14)
Aug 07 02:14:30 mypi roomba-api[482]:     at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:110:7)
Aug 07 02:14:30 mypi roomba-api[482]:     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
Aug 07 02:14:56 mypi roomba-api[482]: GET / 200 2.594 ms - 89

**Comment by koalazak** [comment]
`ROBOT_IP` env var is missing
