### ISSUE TITLE
{ } - Empty responses received ?

### ISSUE THREAD

**Issue by nodecentral** [koalazak/rest980#74]
Hi, I’ve set up the Docker instance on my QNAP and If i go to `192.168.1.111:3000`, it presents the following, 
````
{"documentation":"https://github.com/koalazak/rest980","pong":"2022-09-22T22:03:17.269Z"}
````
but if I try any other API call, e.g `192.168.1.111:3000/api/local/info/state`, i just get an empty response ?
````
{ }
````
In the Docker console it reports the following, which I assume the 200 is a success code, and 2 is bytes received ?
````
GET 200 0.540 ms - 89
GET /api/local/info/state 200 101.331 ms - 2
GET 200 0.541 ms - 89
````
I’m thinking it’s network (connectivity) related, but wanted to see if anyone has any other  ideas ?

**Comment by pgregg88** [comment]
@nodecentral  I'm experiencing the same thing. Did you find a resolution?

**Comment by nodecentral** [comment]
Hi @pgregg88 

I'm afraid not, i still get the empty response ..

Keep hoping it will get fixed... one day.

**Comment by mviniciusleal** [comment]
I had the same problem, for my this was caused by a tls handshake failure.
In the "node_modules/dorita980/lib/v2/local.js" i changed the ciphers to _ciphers: ''_  and it worked.
maybe if you set the environment variable ROBOT_CIPHERS to a empty string could work too.
