### ISSUE TITLE
Request received but no answer

### ISSUE THREAD

**Issue by ThibaultMoka** [koalazak/rest980#76]
Hello,
First of all, thank you for your work. 
I try to make my first request work. 

The request is good received by the server, but then I don't have any response or action on my Roomba. 

There is my Rasp console : 

thibault@raspberrypi:~/rest980 $ DEBUG=rest980:* npm start

> rest980@2.1.2 start
> node ./bin/www

  rest980:server Listening on port 3000 +0ms
GET /api/local/action/start - - ms - -
GET /api/local/action/start - - ms - -

Thank you

**Comment by koalazak** [comment]
are you configuring everything via .json conf file? (I mean robot ip, pass, etc)
