### ISSUE TITLE
Request for https in rest980 + patch

### ISSUE THREAD

**Issue by soosp** [koalazak/rest980#8]
Hi, 
[rest980-https.txt](https://github.com/koalazak/rest980/files/673339/rest980-https.txt)

Thank you for this great project! I played for hours with it and my Roomba.
I created a simple patch to make it possible to use it over https.

**Comment by koalazak** [comment]
Hi @soosp,

sounds good. I will use your patch as inspiration to implement httos in rest980. (i will use the actual default.json config file insetead of a new config file)

thanks!

**Comment by koalazak** [comment]
pushed on https://github.com/koalazak/rest980/commit/9ab6a0029aadf4ab5288cab91905345cf8b6e3b8

thanks!
